export type BranchMapping = {
  posCode: string;
  posName: string;
  grabName: string | null;
};

export const branchMappings: BranchMapping[] = [
  { posCode: "AMK", posName: "GILIGAN'S AYALA MALL MARIKINA", grabName: "Giligan's Restaurant - Ayala Marikina" },
  { posCode: "ANG", posName: "Marquee Mall", grabName: "Giligan's Restaurant - Ayala Marquee" },
  { posCode: "ANO", posName: "GILIGAN'S SM ANGONO RIZAL", grabName: "Giligan's Restaurant - SM Center Angono" },
  { posCode: "AOL", posName: "GILIGAN'S ABOITIZ OUTLET LIPA", grabName: null },
  { posCode: "ASP", posName: "GILIGAN'S AYALA SOUTHPARK", grabName: "Giligan's Restaurant - Ayala Mall South Park" },
  { posCode: "AST", posName: "GILIGAN'S AYALA MALLS SERIN", grabName: null },
  { posCode: "BAC", posName: "GILIGAN'S SM CITY BACOLOD", grabName: "Giligan's Restaurant - SM City Bacolod" },
  { posCode: "BAG", posName: "Giligan's Baguio", grabName: "Giligan's Restaurant - Baguio City" },
  { posCode: "BAL", posName: "GILIGAN'S SM BALIWAG", grabName: "Giligan's Restaurant - SM Baliwag" },
  { posCode: "BAT", posName: "GILIGAN'S SM BATANGAS CITY", grabName: null },
  { posCode: "CAB", posName: "GILIGAN'S SM CABANATUAN", grabName: null },
  { posCode: "CAL", posName: "GILIGAN'S SM CALAMBA", grabName: "Giligan's Restaurant - SM Calamba" },
  { posCode: "CHR", posName: "GILIGAN'S SM CHERRY ANTIPOLO", grabName: "Giligan's Restaurant - SM Cherry Antipolo" },
  { posCode: "CIR", posName: "GILIGAN'S CIRCULO VERDE", grabName: "Giligan's Restaurant - Circulo Verde" },
  { posCode: "CLK", posName: "GILIGAN'S SM CITY CLARK", grabName: "Giligan's Restaurant - SM City Clark" },
  { posCode: "CM1", posName: "GILIGAN'S CIRCUIT MAKATI", grabName: "Giligan's Restaurant - Circuit Makati" },
  { posCode: "FEX", posName: "GILIGAN'S FESTIVAL EXPANSION", grabName: "Giligan's Restaurant - Festival Mall Extension" },
  { posCode: "GBR", posName: "GILIGAN'S GAISANO BINANGONAN RIZAL", grabName: "Gaisano Binangonan Rizal" },
  { posCode: "GHL", posName: "GILIGAN'S GREENHILLS", grabName: "Giligan's Restaurant - Greenhills" },
  { posCode: "GIR", posName: "GILIGAN'S GAISANO IRIGA", grabName: null },
  { posCode: "HEC", posName: "GILIGAN'S HYPERMARKET CUBAO", grabName: null },
  { posCode: "HFT", posName: "GILIGAN'S HYPERMARKET FTI", grabName: "Giligan's Restaurant - SM Hypermarket FTI" },
  { posCode: "HIC", posName: "GILIGAN'S HYPERMARKET IMUS CAVITE", grabName: "Giligan's Restaurant - SM Hypermarket Imus" },
  { posCode: "HQN", posName: "GILIGAN'S SM HYPERMARKET NOVALICHES", grabName: null },
  { posCode: "HSL", posName: "GILIGAN'S HYPERMARKET SUCAT-LOPEZ", grabName: "Giligan's Restaurant - SM Hypermarket Sucat-Lopez" },
  { posCode: "IL2", posName: "GILIGAN'S SM CITY ILOILO", grabName: "Giligan's Restaurant - SM Iloilo Southpoint" },
  { posCode: "IMU", posName: "GILIGAN'S 5M IMUS", grabName: "Giligan's Restaurant - SM Center Imus" },
  { posCode: "JAC", posName: "GILIGAN'S JACKMAN PLAZA MUNOZ", grabName: "Giligan's Restaurant - Jackman Plaza Munoz" },
  { posCode: "LCI", posName: "GILIGAN'S LANCASTER CITY IMUS", grabName: "Giligan's Restaurant - Lancaster Imus" },
  { posCode: "LEM", posName: "GILIGAN'S 5M LEMERY", grabName: null },
  { posCode: "LIP", posName: "ROBINSONS PLACE LIPA", grabName: "Giligan's Restaurant - Robinsons Lipa" },
  { posCode: "LOR", posName: "GILIGAN'S SAN LORENZO PLACE", grabName: "Giligan's Restaurant - San Lorenzo Place Makati" },
  { posCode: "LUC", posName: "GILIGAN'S SM LUCENA", grabName: null },
  { posCode: "MAR", posName: "Market! Market!", grabName: "Giligan's Restaurant - Ayala Market Market" },
  { posCode: "MIL", posName: "GILIGAN'S MILLE LUCE", grabName: "Giligan's Restaurant - Mille Luce Antipolo" },
  { posCode: "MOA", posName: "SM by the Bay", grabName: "Giligan's Restaurant - SM Mall of Asia" },
  { posCode: "MOD", posName: "GILIGAN'S MOADTO STRIP MALL", grabName: null },
  { posCode: "MSM", posName: "GILIGAN'S MAIN SQUARE MOLINO", grabName: "Giligan's Restaurant - Main Square Molino" },
  { posCode: "MUN", posName: "GILIGAN'S SM CENTER MUNTINLUPA", grabName: "Giligan's Restaurant - SM Center Muntinlupa" },
  { posCode: "NOR", posName: "GILIGAN'S SMNE SKY GARDEN", grabName: "Giligan's Restaurant - SM City North Edsa" },
  { posCode: "NOV", posName: "GILIGAN'S SM NOVALICHES", grabName: "Giligan's Restaurant - SM Novaliches" },
  { posCode: "NPC", posName: "GILIGAN'S NEWPORT CITY", grabName: "Giligan's Restaurant - Newport City" },
  { posCode: "NPN", posName: "GILIGAN'S NOVA PLAZA MALL", grabName: null },
  { posCode: "OMV", posName: "GILIGAN'S ONEMALL VALENZUELA", grabName: "Giligan's Restaurant - One Mall Valenzuela" },
  { posCode: "PAC", posName: "GILIGAN'S PACO MALL", grabName: "Giligan's Restaurant - Paco Mall" },
  { posCode: "PCJ", posName: "PUREGOLD CAINTA JUNCTION", grabName: "Giligan's Restaurant - Puregold Cainta Junction" },
  { posCode: "PED", posName: "GILIGAN'S ROBINSONS SAN PEDRO", grabName: "Giligan's Restaurant - Robinsons Galleria South" },
  { posCode: "PSG", posName: "GILIGAN'S SM PASIG", grabName: "Giligan's Restaurant - SM Center Pasig" },
  { posCode: "PUL", posName: "GILIGAN'S SM PULILAN", grabName: "Giligan's Restaurant - SM Center Pulilan" },
  { posCode: "RBC", posName: "GILIGAN'S THE PLAZA BAGONG SILANG", grabName: null },
  { posCode: "REA", posName: "GILIGAN'S ROBINSONS PLACE ANTIPOLO", grabName: null },
  { posCode: "RGT", posName: "GILIGAN'S ROBINSONS GEN TRIAS", grabName: null },
  { posCode: "RIV", posName: "GILIGAN'S RIVERBANKS MARIKINA", grabName: "Giligan's Restaurant - Riverbanks Center Marikina" },
  { posCode: "RNG", posName: "GILIGAN'S ROBINSONS NAGA", grabName: null },
  { posCode: "SCL", posName: "GILIGAN'S SM CENTER LAS PIÑAS", grabName: null },
  { posCode: "SDH", posName: "GILIGAN'S DAANG HARI", grabName: "Giligan's Restaurant - Vista Mall Daang Hari" },
  { posCode: "SFV", posName: "GILIGAN'S SM FAIRVIEW", grabName: "Giligan's Restaurant - SM City Fairview" },
  { posCode: "SGD", posName: "GILIGAN'S SM SANGANDAAN", grabName: "Giligan's Restaurant - SM Center Sangandaan" },
  { posCode: "SLE", posName: "GILIGAN'S IL CENTRO", grabName: "Giligan's Restaurant - Santa Lucia East Grand Mall" },
  { posCode: "SML", posName: "GILIGAN'S SM CITY MOLINO", grabName: "Giligan's Restaurant - SM Center Molino" },
  { posCode: "SOU", posName: "GILIGAN'S SOUTHMALL", grabName: "Giligan's Restaurant - SM City Southmall" },
  { posCode: "SPP", posName: "GILIGAN'S SM CITY PUERTO PRINCESA", grabName: null },
  { posCode: "SRC", posName: "GILIGAN'S SM ROSARIO", grabName: "Giligan's Restaurant - SM Rosario" },
  { posCode: "SSI", posName: "GILIGAN'S SM SAN JOSE BRANCH", grabName: "Giligan's Restaurant - SM San Jose Del Monte" },
  { posCode: "SSP", posName: "GILIGAN'S SM SAN PEDRO", grabName: "Giligan's Restaurant - SM Center San Pedro" },
  { posCode: "SSS", posName: "GILIGAN'S SM SEASIDE CEBU", grabName: "Giligan's Restaurant - SM Seaside Cebu" },
  { posCode: "STG", posName: "GILIGAN'S STARMALL TAGUIG", grabName: "Giligan's Restaurant - Starmall Taguig" },
  { posCode: "SWM", posName: "GILIGAN'S SOUTHWOODS MALL", grabName: "Giligan's Restaurant - Southwoods Mall Binan" },
  { posCode: "TAG", posName: "GILIGAN'S TAGAYTAY", grabName: "Giligan's Restaurant - Robinsons Tagaytay" },
  { posCode: "TAY", posName: "GILIGAN'S SM TAYTAY", grabName: "Giligan's Restaurant - SM Taytay" },
  { posCode: "TEL", posName: "GILIGAN'S SM TELABASTAGAN", grabName: "Giligan's Restaurant - SM Telebastagan" },
  { posCode: "VAL", posName: "GILIGAN'S SM CITY VALENZUELA", grabName: "Giligan's Restaurant - SM Valenzuela" },
  { posCode: "VER", posName: "GILIGAN'S VERDANT", grabName: "Giligan's Restaurant - Verdant Strip" },
  { posCode: "VMB", posName: "GILIGAN'S VISTAMALL MALOLOS", grabName: "Giligan's Restaurant - Vista Mall Malolos" },
  { posCode: "VMD", posName: "GILIGAN'S VISTAMALL DASMARINAS", grabName: "Giligan's Restaurant - Vista Mall Dasmarinas" },
  { posCode: "VMS", posName: "GILIGAN'S VICTORY MALL STA. ROSA", grabName: null },
  { posCode: "VST", posName: "GILIGAN'S VISTAMALL SAN FERNANDO", grabName: "Giligan's Restaurant - Vista Mall San Fernando" },
  { posCode: "VSP", posName: "GILIGAN'S VILLAR SIPAG", grabName: "Giligan's Restaurant - Villar Sipag Las Pinas" },
  { posCode: "VSR", posName: "GILIGAN'S VISTAMALL SANTA ROSA", grabName: "Giligan's Restaurant - Vista Mall Santa Rosa" },
  { posCode: "VTZ", posName: "GILIGAN'S VISTAMALL TANZA", grabName: "Giligan's Restaurant - Vista Mall Tanza" },
  { posCode: "WNB", posName: "GILIGAN'S WALTERMART NASUGBU", grabName: null },
  { posCode: "WPT", posName: "GILIGAN'S WM PANIQUI", grabName: null },
  { posCode: "WSM", posName: "GILIGAN'S WALTERMART STA.MARIA", grabName: "Giligan's Restaurant - Walter Mart Sta. Maria" },
  { posCode: "WVC", posName: "GILIGAN'S WILCON CITY CENTER", grabName: "Giligan's Restaurant - Wilcon Visayas Avenue" }
];
